# Generated by Django 3.2 on 2023-08-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.RemoveField(
            model_name='note',
            name='owner',
        ),
    ]
